import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AppWrappers from "./AppWrappers";
import React, { ReactNode } from "react";
import AdminLayout from '@/layouts/admin';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body id={"root"}>
        <AppWrappers>
          <AdminLayout>{children}</AdminLayout>
        </AppWrappers>
      </body>
    </html>
  );
}

